// <auto-generated />
using System;
using CRMSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRMSystem.API.Migrations
{
    [DbContext(typeof(ContextoBDCRM))]
    partial class ContextoBDCRMModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRMSystem.API.Models.CategoriaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasCliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Clientes premium con descuento máximo",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5464),
                            NombreCategoria = "Premium",
                            PorcentajeDescuento = 20.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Clientes corporativos con descuento medio",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5476),
                            NombreCategoria = "Corporativo",
                            PorcentajeDescuento = 15.00m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Clientes regulares con descuento estándar",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5477),
                            NombreCategoria = "Regular",
                            PorcentajeDescuento = 10.00m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Clientes nuevos con descuento mínimo",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5479),
                            NombreCategoria = "Nuevo",
                            PorcentajeDescuento = 5.00m
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaPadreId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.ToTable("CategoriasProducto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Equipos y componentes físicos",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5597),
                            NombreCategoria = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Licencias y aplicaciones de software",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5607),
                            NombreCategoria = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Servicios profesionales y consultoría",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5608),
                            NombreCategoria = "Servicios"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Servicios de mantenimiento y soporte",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5610),
                            NombreCategoria = "Mantenimiento"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Cursos y capacitación técnica",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5616),
                            NombreCategoria = "Capacitación"
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimaCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Industria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ValorVidaCliente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendedorAsignadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoCliente")
                        .IsUnique();

                    b.HasIndex("NombreEmpresa");

                    b.HasIndex("RFC");

                    b.HasIndex("SucursalId");

                    b.HasIndex("VendedorAsignadoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CRMSystem.API.Models.ContactoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EsContactoPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCumpleanos")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoDirecto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefonoMovil")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ContactosCliente");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoAdjunto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("CondicionesPago")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmailCliente")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoCotizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCotizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("NumeroCotizacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeIVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProspectoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TerminosCondiciones")
                        .HasColumnType("text");

                    b.Property<string>("TiempoEntrega")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Vigencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoCotizacion");

                    b.HasIndex("FechaCotizacion");

                    b.HasIndex("NumeroCotizacion")
                        .IsUnique();

                    b.HasIndex("ProspectoId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("CRMSystem.API.Models.DetalleCotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesCotizacion");
                });

            modelBuilder.Entity("CRMSystem.API.Models.EventoCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("DescripcionEvento")
                        .HasColumnType("text");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatronRecurrencia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ProspectoId")
                        .HasColumnType("integer");

                    b.Property<int?>("Recordatorio")
                        .HasColumnType("integer");

                    b.Property<string>("TipoEvento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("TodoElDia")
                        .HasColumnType("boolean");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("ProspectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EventosCalendario");
                });

            modelBuilder.Entity("CRMSystem.API.Models.FuenteProspecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreFuente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoFuente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FuentesProspecto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Exposición industrial anual",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5531),
                            NombreFuente = "Expo Industrial 2024",
                            TipoFuente = "Expo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Campaña de marketing digital primer trimestre",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5539),
                            NombreFuente = "Campaña Digital Q1",
                            TipoFuente = "Campaña"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Referencia de cliente existente",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5540),
                            NombreFuente = "Referido Cliente",
                            TipoFuente = "Referido"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Formulario de contacto en sitio web",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5541),
                            NombreFuente = "Sitio Web",
                            TipoFuente = "Web"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Prospección telefónica directa",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5543),
                            NombreFuente = "Llamada Fría",
                            TipoFuente = "Llamada Fría"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Red social profesional",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5544),
                            NombreFuente = "LinkedIn",
                            TipoFuente = "Redes Sociales"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Eventos de networking empresarial",
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5545),
                            NombreFuente = "Evento Networking",
                            TipoFuente = "Evento"
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Especificaciones")
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagenURL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioLista")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoEntrega")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            CodigoProducto = "HW-001",
                            Descripcion = "Servidor rack 2U con procesador Intel Xeon",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5713),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5712),
                            Moneda = "MXN",
                            NombreProducto = "Servidor Dell PowerEdge R740",
                            PrecioCosto = 65000.00m,
                            PrecioLista = 85000.00m,
                            Stock = 0,
                            StockMinimo = 0,
                            TiempoEntrega = 0,
                            UnidadMedida = "Pieza"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            CodigoProducto = "SW-001",
                            Descripcion = "Suite de productividad empresarial",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5724),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5723),
                            Moneda = "MXN",
                            NombreProducto = "Licencia Microsoft Office 365 Business",
                            PrecioCosto = 1800.00m,
                            PrecioLista = 2500.00m,
                            Stock = 0,
                            StockMinimo = 0,
                            TiempoEntrega = 0,
                            UnidadMedida = "Pieza"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            CodigoProducto = "SV-001",
                            Descripcion = "Análisis y diseño de infraestructura",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5727),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5727),
                            Moneda = "MXN",
                            NombreProducto = "Consultoría de Infraestructura TI",
                            PrecioCosto = 8000.00m,
                            PrecioLista = 15000.00m,
                            Stock = 0,
                            StockMinimo = 0,
                            TiempoEntrega = 0,
                            UnidadMedida = "Pieza"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            CodigoProducto = "HW-002",
                            Descripcion = "Laptop empresarial con Intel Core i7",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5730),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5729),
                            Moneda = "MXN",
                            NombreProducto = "Laptop HP EliteBook 840 G8",
                            PrecioCosto = 22000.00m,
                            PrecioLista = 28000.00m,
                            Stock = 0,
                            StockMinimo = 0,
                            TiempoEntrega = 0,
                            UnidadMedida = "Pieza"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            CodigoProducto = "SW-002",
                            Descripcion = "Sistema operativo servidor",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5732),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5732),
                            Moneda = "MXN",
                            NombreProducto = "Licencia Windows Server 2022 Standard",
                            PrecioCosto = 9000.00m,
                            PrecioLista = 12000.00m,
                            Stock = 0,
                            StockMinimo = 0,
                            TiempoEntrega = 0,
                            UnidadMedida = "Pieza"
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.Prospecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CargoContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoProspecto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoDireccion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoProspecto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaConversion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEstimadaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FuenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Industria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ProbabilidadCierre")
                        .HasColumnType("integer");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("TamanoEmpresa")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendedorAsignadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProspecto")
                        .IsUnique();

                    b.HasIndex("EstadoProspecto");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("FuenteId");

                    b.HasIndex("SucursalId");

                    b.HasIndex("VendedorAsignadoId");

                    b.ToTable("Prospectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoContacto = "Ramírez",
                            CodigoProspecto = "PROS-2024-001",
                            Email = "cramirez@tecavanzada.com",
                            EstadoProspecto = "Nuevo",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5765),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5764),
                            FuenteId = 1,
                            NombreContacto = "Carlos",
                            NombreEmpresa = "Tecnología Avanzada SA",
                            Pais = "México",
                            Prioridad = "Media",
                            ProbabilidadCierre = 0,
                            SucursalId = 1,
                            Telefono = "+52-81-5555-1234",
                            ValorEstimado = 150000.00m,
                            VendedorAsignadoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApellidoContacto = "Martínez",
                            CodigoProspecto = "PROS-2024-002",
                            Email = "lmartinez@solempresariales.com",
                            EstadoProspecto = "Nuevo",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5784),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5783),
                            FuenteId = 2,
                            NombreContacto = "Laura",
                            NombreEmpresa = "Soluciones Empresariales MX",
                            Pais = "México",
                            Prioridad = "Media",
                            ProbabilidadCierre = 0,
                            SucursalId = 2,
                            Telefono = "+52-33-5555-5678",
                            ValorEstimado = 85000.00m,
                            VendedorAsignadoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApellidoContacto = "Hernández",
                            CodigoProspecto = "PROS-2024-003",
                            Email = "fhernandez@gis.com",
                            EstadoProspecto = "Nuevo",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5788),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5788),
                            FuenteId = 3,
                            NombreContacto = "Fernando",
                            NombreEmpresa = "Grupo Industrial del Sureste",
                            Pais = "México",
                            Prioridad = "Media",
                            ProbabilidadCierre = 0,
                            SucursalId = 3,
                            Telefono = "+52-99-5555-9012",
                            ValorEstimado = 220000.00m,
                            VendedorAsignadoId = 4
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Permisos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RolesUsuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Representante de ventas",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4969),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4967),
                            NombreRol = "Vendedor",
                            Permisos = "[\"prospectos:leer\", \"prospectos:crear\", \"clientes:leer\", \"tareas:gestionar\"]"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Especialista en cotizaciones",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4978),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4977),
                            NombreRol = "Cotizador",
                            Permisos = "[\"cotizaciones:gestionar\", \"productos:leer\", \"clientes:leer\"]"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Gerente de área",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4980),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4979),
                            NombreRol = "Gerente",
                            Permisos = "[\"prospectos:gestionar\", \"cotizaciones:gestionar\", \"reportes:leer\", \"equipo:gestionar\"]"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Director de operaciones",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4981),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4981),
                            NombreRol = "Director",
                            Permisos = "[\"todos:leer\", \"todos:gestionar\", \"reportes:avanzados\", \"usuarios:gestionar\"]"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Tecnologías de información",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4983),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4983),
                            NombreRol = "Sistemas",
                            Permisos = "[\"sistema:admin\", \"usuarios:gestionar\", \"datos:exportar\"]"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Contador",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4985),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4984),
                            NombreRol = "Contador",
                            Permisos = "[\"financiero:leer\", \"reportes:financiero\", \"cotizaciones:leer\"]"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Director de sucursal",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4986),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4986),
                            NombreRol = "Director de Sucursal",
                            Permisos = "[\"sucursal:gestionar\", \"reportes:sucursal\", \"equipo:gestionar\"]"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Consejero estratégico",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4988),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4987),
                            NombreRol = "Consejero",
                            Permisos = "[\"reportes:leer\", \"analitica:avanzada\", \"estrategia:ver\"]"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Dirección general",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4989),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(4989),
                            NombreRol = "Dirección General",
                            Permisos = "[\"todos:admin\", \"sistema:configurar\", \"estrategico:gestionar\"]"
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CodigoSucursal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GerenteId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreSucursal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSucursal")
                        .IsUnique();

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ciudad = "Monterrey",
                            CodigoSucursal = "NORTE",
                            Direccion = "Av. Revolución 1234",
                            Email = "norte@crm.com",
                            EstaActivo = true,
                            Estado = "Nuevo León",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5222),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5222),
                            NombreSucursal = "Sucursal Norte",
                            Telefono = "+52-81-1234-5678"
                        },
                        new
                        {
                            Id = 2,
                            Ciudad = "Guadalajara",
                            CodigoSucursal = "CENTRO",
                            Direccion = "Av. Juárez 5678",
                            Email = "centro@crm.com",
                            EstaActivo = true,
                            Estado = "Jalisco",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5248),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5248),
                            NombreSucursal = "Sucursal Centro",
                            Telefono = "+52-33-2345-6789"
                        },
                        new
                        {
                            Id = 3,
                            Ciudad = "Mérida",
                            CodigoSucursal = "SUR",
                            Direccion = "Av. Insurgentes 9012",
                            Email = "sur@crm.com",
                            EstaActivo = true,
                            Estado = "Yucatán",
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5252),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5252),
                            NombreSucursal = "Sucursal Sur",
                            Telefono = "+52-99-3456-7890"
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignadoA")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("CotizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionTarea")
                        .HasColumnType("text");

                    b.Property<string>("EstadoTarea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ProspectoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTarea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoA");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("EstadoTarea");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("ProspectoId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            Email = "jperez@crm.com",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5651),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5650),
                            HashContrasena = "hash123",
                            Nombre = "Juan",
                            NombreUsuario = "jperez",
                            RolId = 1,
                            SucursalId = 1
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "García",
                            Email = "mgarcia@crm.com",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5674),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5674),
                            HashContrasena = "hash456",
                            Nombre = "María",
                            NombreUsuario = "mgarcia",
                            RolId = 2,
                            SucursalId = 2
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "López",
                            Email = "rlopez@crm.com",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5678),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5677),
                            HashContrasena = "hash789",
                            Nombre = "Roberto",
                            NombreUsuario = "rlopez",
                            RolId = 3,
                            SucursalId = 1
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Sánchez",
                            Email = "asanchez@crm.com",
                            EstaActivo = true,
                            FechaActualizacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5682),
                            FechaCreacion = new DateTime(2025, 11, 27, 20, 10, 35, 206, DateTimeKind.Utc).AddTicks(5681),
                            HashContrasena = "hash101",
                            Nombre = "Ana",
                            NombreUsuario = "asanchez",
                            RolId = 1,
                            SucursalId = 3
                        });
                });

            modelBuilder.Entity("CRMSystem.API.Models.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asistentes")
                        .HasColumnType("text");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionVisita")
                        .HasColumnType("text");

                    b.Property<string>("DocumentosAdjuntos")
                        .HasColumnType("text");

                    b.Property<int?>("Duracion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaProximaAccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProspectoId")
                        .HasColumnType("integer");

                    b.Property<string>("ProximaAccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Resultado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoVisita")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProspectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("CRMSystem.API.Models.CategoriaProducto", b =>
                {
                    b.HasOne("CRMSystem.API.Models.CategoriaProducto", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Cliente", b =>
                {
                    b.HasOne("CRMSystem.API.Models.CategoriaCliente", "Categoria")
                        .WithMany("Clientes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Sucursal", "Sucursal")
                        .WithMany("Clientes")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Usuario", "VendedorAsignado")
                        .WithMany("ClientesAsignados")
                        .HasForeignKey("VendedorAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Sucursal");

                    b.Navigation("VendedorAsignado");
                });

            modelBuilder.Entity("CRMSystem.API.Models.ContactoCliente", b =>
                {
                    b.HasOne("CRMSystem.API.Models.Cliente", "Cliente")
                        .WithMany("Contactos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Cotizacion", b =>
                {
                    b.HasOne("CRMSystem.API.Models.Cliente", "Cliente")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Prospecto", "Prospecto")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Sucursal", "Sucursal")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Usuario", "Vendedor")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Prospecto");

                    b.Navigation("Sucursal");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("CRMSystem.API.Models.DetalleCotizacion", b =>
                {
                    b.HasOne("CRMSystem.API.Models.Cotizacion", "Cotizacion")
                        .WithMany("Detalles")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Producto", "Producto")
                        .WithMany("DetallesCotizacion")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CRMSystem.API.Models.EventoCalendario", b =>
                {
                    b.HasOne("CRMSystem.API.Models.Cliente", "Cliente")
                        .WithMany("Eventos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Prospecto", "Prospecto")
                        .WithMany("Eventos")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Usuario", "Usuario")
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Prospecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Producto", b =>
                {
                    b.HasOne("CRMSystem.API.Models.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Prospecto", b =>
                {
                    b.HasOne("CRMSystem.API.Models.FuenteProspecto", "Fuente")
                        .WithMany("Prospectos")
                        .HasForeignKey("FuenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Sucursal", "Sucursal")
                        .WithMany("Prospectos")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Usuario", "VendedorAsignado")
                        .WithMany("ProspectosAsignados")
                        .HasForeignKey("VendedorAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fuente");

                    b.Navigation("Sucursal");

                    b.Navigation("VendedorAsignado");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Tarea", b =>
                {
                    b.HasOne("CRMSystem.API.Models.Usuario", "UsuarioAsignado")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("AsignadoA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Cliente", "Cliente")
                        .WithMany("Tareas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Cotizacion", "Cotizacion")
                        .WithMany()
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Usuario", "UsuarioCreador")
                        .WithMany("TareasCreadas")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Prospecto", "Prospecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Cotizacion");

                    b.Navigation("Prospecto");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Usuario", b =>
                {
                    b.HasOne("CRMSystem.API.Models.RolUsuario", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRMSystem.API.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Visita", b =>
                {
                    b.HasOne("CRMSystem.API.Models.Cliente", "Cliente")
                        .WithMany("Visitas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Prospecto", "Prospecto")
                        .WithMany("Visitas")
                        .HasForeignKey("ProspectoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRMSystem.API.Models.Usuario", "Usuario")
                        .WithMany("Visitas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Prospecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CRMSystem.API.Models.CategoriaCliente", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("CRMSystem.API.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Cliente", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Cotizaciones");

                    b.Navigation("Eventos");

                    b.Navigation("Tareas");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Cotizacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CRMSystem.API.Models.FuenteProspecto", b =>
                {
                    b.Navigation("Prospectos");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Producto", b =>
                {
                    b.Navigation("DetallesCotizacion");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Prospecto", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("Eventos");

                    b.Navigation("Tareas");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("CRMSystem.API.Models.RolUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Sucursal", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Cotizaciones");

                    b.Navigation("Prospectos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CRMSystem.API.Models.Usuario", b =>
                {
                    b.Navigation("ClientesAsignados");

                    b.Navigation("Cotizaciones");

                    b.Navigation("Eventos");

                    b.Navigation("ProspectosAsignados");

                    b.Navigation("TareasAsignadas");

                    b.Navigation("TareasCreadas");

                    b.Navigation("Visitas");
                });
#pragma warning restore 612, 618
        }
    }
}
